spring:
  flyway:
    out-of-order: true
    ignore-missing-migrations: true
    schemas: public
  datasource:
    driver-class-name:
      org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/biom
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
app:
  jwtSecret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  jwtExpirationMs: 86400000