spring:
  mvc:
    format:
      date: dd/MM/yyyy
  datasource:
    driver-class-name:
      org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/biom_db
    username: postgres
    password: kennys0
  flyway:
    schemas: biom
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
jwt:
  secret: secret
  time-life: 30
server:
  port: 8081