spring:
  flyway:
    out-of-order: true
    ignore-missing-migrations: true
    schemas: biom
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  datasource:
    driver-class-name:
      org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=biom
    username: postgres
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  messages:
    basename: validation
server:
  port: 8081